### ISSUE TITLE
Graphical issues with electron / chromium apps

### ISSUE THREAD

**Issue by mustneerar7** [zearp/OptiHack#31]
Hi,
I tried out the EFI you provided. It works great with catalina but with big sur 11.0.1 there's some graphical issues. Graphics do accelerate but electron apps ( web based apps with chromium v8 engine ) have issues rendering text and images. If I disable acceleration then they render correctly but it makes apps like Figma useless.

My system is an Optiplex 7020 SFF, an i3 4150 with HD Graphics 4400 and no expansion cards.
Cheers,

**Comment by mgrimace** [comment]
Hello @mustneerar7, 

This build is built around an HD4600 iGPU from the i5 version of the Haswell processor and the HD4400 iGPU is unsupported in macOS. The good news is that the `device-ID` line in Device Properties of the config.plist is used to fake/spoof the Device ID for HD4600 which does have support in macOS ([source](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html#deviceproperties)). This is why it was likely working under Catalina.  Please note that I'm not at all sure if the frame buffer settings we've added in the config.plist here for the HD4600 are correct for the HD4400.

I'm guessing you're experiencing difficulty on Big Sur because some of the Device Properties values we're using for the HD4600 aren't fully working yet in Big Sur (i.e., all userspace-based patches). Which, in turn means they also won't be applying properly to your spoofed HD4400. It could also be related to limitations of the hardware, or some combination of both.

Options would be to wait for WhateverGreen and Lilu to update support for userspace patches and see if those fix the issues you're having, downgrade, or attempt to patch things manually (see this [thread](https://github.com/zearp/OptiHack/issues/27#issuecomment-743784568), but again ++caution since we're referring to the HD4**6**00.

**Comment by mustneerar7** [comment]
Thanks for the guidance ☺️
It might be too advance for me to patch a kext. For time being I'll stay on catalina and try new kexts on a separate EFI on secondary SSD.

**Comment by zearp** [comment]
The HD4400 is notorious for its glitches. The best solution is to find a nice second hand i5/i7 and upgrade.

Spend a lot of hours here trying to get the HD4400 to work and it was always a bit glitchy. This is partly due to no Mac ever being sold with that chip. There is no support for it in the driver. Which is why you get glitches despite everything being setup correctly.

Save yourself the time and headache and look for another processor. I have not seen a single config using this chip that didn’t have glitches. I kept one i3 as a keepsake. The solution to this is most likely rewriting/fixing the Azul kext itself. Something I can’t do. The HD4600 is natively supported and works great.

Good luck!

**Comment by mustneerar7** [comment]
Thanks @zearp for clearing things out ☺️

Yeah instead of going through all of this headache I should simply get a used haswell i5/i7 with 4600 graphics. (They're dirt cheap nowadays anyway). 

Just a quick question
Does macOS natively support low powered  amd cards( from low powered i mean cards which fit in a SFF chasis and don't require power other than PCIE ) like radeon R7? If yes then i might have one lying around. I could disable iGPU all together and just use dGPU

**Comment by zearp** [comment]
They're pretty cheap, cheaper than buying a video card for me. And you get some decent performance improvements too. The older i3 series was not as good as the current i3 generation. I picked up some i5 4570S processors for about $20 a piece. There are better processors to get but I quite like the S models, fast enough for my needs and a little bit less power hungry with a tdp of 65watts. Easy to keep cool too and it performs about 3% slower than the normal 4570.

I kept one i3 as a spare but gave up on trying to make it work. It was working as best as it could but the glitches never went away completely. Tried spoofing different HD4x00 series and tried different WEG options and platform id's and what not, but at some point the time spend on it is not worth it anymore considering a new processor is pretty cheap.

I'm not sure which cards are supported that would fit and won't tax the psu too much. You need something low profile, low watts and ideally passively cooled. The front intake fan will blow air over it so it shouldn't get super hot. Instead of disabling you can run the iGPU in compute mode. It can do video decoding and some other stuff. You just remove the iGPU section from the config and WhateverGreen will do the rest.

One benefit of a dedicated card would be properly working DRM, although I'm not sure if the works on Big Sur yet. It may depend on the model. Not having working DRM with intel graphics is one reason I consider getting a card but it must be cheap and silent haha. Hope you can sort it out soon.

**Comment by mustneerar7** [comment]
Yeah thanks for the advice 😊

I'll try the GPU if it works I'll let you know
Radeon R7 cards are old but really cheap. I originally got it for a system with no iGPU and it was about $35 used.

The best plan seems to get an i5 with 4600 graphics. Even if I decide to use Windows or Linux performance gains would be worth it.

Once again thanks man for your help and awesome work. Keep it up!

Have a nice day

**Comment by zearp** [comment]
Thank you for the kind words.

I haven't regretted upgrading, despite "giving up" is not really in my nature. For this issue it simply wasn't worth putting in so much time to test and rebooting and hurting my eyes lol. I gained a noticeable difference in speed for very little money spend. Benchmarks suggest that the i3 4160 is about 15% slower than the ones I got. And I didn't get the best ones just the ones easiest to buy.

You could go for an i7, just make sure the tdp and total power draw of the system doesn't go beyond the little psu Dell uses in these small cases. They were sold with i7's so it shouldn't be a problem on paper but a thing to keep in the back of your mind when shopping.

Dell has sold the 7020 with the i7 4790 which has an 84watts tdp. It would be an awesome upgrade if you can find one of those. It has 4 cores and 8 threads and will last at least another couple of years. Upgrading to the i5 which has 4 cores/4 threads will be a nice improvement over the dual core i3 too.
