### ISSUE TITLE
Similar build, AppleALC problem

### ISSUE THREAD

**Issue by BrunoGM** [zearp/OptiHack#32]
Hi, I use a build that is similar to yours, with an i7 4790k and Intel HD4600. Your EFI works perfectly with everything except sound. When i try changing the alcid to alcid=1(from alc1150) I get kernel panic. Do you have some idea of what could be causing this? Thanks

**Comment by zearp** [comment]
I have no idea, trying different audio layouts shouldn't trigger a panic. Does it happen with every layout you try or just some layouts?

I think while the EFI seems to work there could be some compatibility issue thats causing a panic where a panic shouldn't happen. All the ACPI patches are made to work on 7020/9020 and might not work properly or cause these kind of weird issues on other systems. Like the IRQ/HPET fixes are very specific to the system. I don't recommend using them on anything else. 

Not all patches aren't strictly needed (but highly recommended) so for now see if disabling ```SSDT-HPET.aml``` and ```SSDT-SBUS-MCHC.aml``` in the config helps. I'm guessing the EC/PLUG patches work due to same chipsets maybe, but I'd also make those from scratch if I were you.

Making your own is very easy and while not strictly required you should make them for optimal stability. You can pretty much automate making most of them. Check out: https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html

The SSDTTime tool can generate all the patches needed and it can also extract the DSDT from your system if on't have a dump of it yet and run it in Windows or Linux. It will generate ```.aml``` files and also a file with some patches you need to add to the config.

I'll close the issue since it's out of the scope of this repo but I do hope you can sort the panic out by either disabling those ACPI patches or better; making your own.

One more option that comes to mind is that maybe the version of AppleALC in the EFI has some issue. But that is very unlikely, but you can still try replacing it with a release version found [here](https://github.com/acidanthera/AppleALC/releases). I compile all kexts on this repo using the latest sources and sometimes a little bug can sneak in.

Good luck!

**Comment by BrunoGM** [comment]
Thank you very much for your time and help and for the good ideas, gonna try those out ASAP. Congrats for the awesome repo.

**Comment by zearp** [comment]
You're welcome. Hope you can sort the panics and find the correct layout to get audio working on your build.
