### ISSUE TITLE
airplay

### ISSUE THREAD

**Issue by mbatrawi** [zearp/OptiHack#34]
is Airplay working with optiplex 9020  and Big sur?
if yes can you explain?

**Comment by zearp** [comment]
Yes. As long as your airplay device is connected to the same network it will work. I use some of the old power brick style ones wired and wirelessly and they’re detected on all my machines just fine.

**Comment by mbatrawi** [comment]
I have both connected to same network but not detect my apple tv in big sur
only detect in catalina
what I should do to work in big sur

**Comment by zearp** [comment]
I don’t know how to troubleshoot that. Some Apple devices can be put in debug mode and allow you can login and run commands. Like the AirPlay bricks run NetBSD.

Apple TV may have something like it too. I don’t know. Check routes and trace route and pings and things like that. 

I’m pretty sure it’s not caused by my config and I’m nit here to give support or help people configure their network. These issues are meant to report bugs not get support.

**Comment by zearp** [comment]
I don’t know how to troubleshoot that. Some Apple devices can be put in debug mode and allow you can login and run commands. Like the AirPlay bricks run NetBSD.

Apple TV may have something like it too. I don’t know. Check routes and trace route and pings and things like that.

I’m pretty sure it’s not caused by my config and I’m not here to give support or help people configure their machine and/or network. The issue system is meant to report bugs not get support.

**Comment by zearp** [comment]
I don’t know how to troubleshoot that. Some Apple devices can be put in debug mode and allow you to login and run commands. Like the AirPlay bricks run NetBSD.

Apple TV may have something like it too. I don’t know. Check routes and trace route and pings and things like that.

I’m pretty sure it’s not caused by my config and I’m not here to give support or help people configure their network. The issue system is meant to report bugs not get support.

**Comment by mbatrawi** [comment]
My Question is airplay working with Ethernet built in or you added a WiFi card?
If yes what is the WiFi card name?

**Comment by zearp** [comment]
The wireless card doesn't matter as long as it is supported. Same for ethernet cards. For supported wireless cards you could check out the [Dortania's buying guide](https://dortania.github.io/Wireless-Buyers-Guide/). The type of network connection also doesn't matter as long as their connected to the same network. My own setup is mixed with bot wired and wirelessly connected Airplay bricks.

They broadcast they're available on your network like a Chromecast/etc do too. So if you can't see it you need to figure out why. I'd start with running a ping/traceroute to the IP of your Airplay device to verify you can actually route packets to it. Maybe it's firewalled or on a different subnet, or maybe your router doesn't route and/or forward all traffic (eg the packets that announce its presence) properly.

There are a lot of options to go by and I can't help you with this any more than I already did. I can't start giving some kind of general tech support here cuz then everybody will start opening issues and except me to help them. Been there, done that. It costs way too much time.

Please use Hackintosh or even Apple related forums or Reddit to get help if you n't sort it out yourself. There are plenty of people who will gladly help you to troubleshoot and help you step by step. This is not the right place for it though.

Good luck!

**Comment by zearp** [comment]
The wireless card doesn't matter as long as its supported by macOS. Same for ethernet cards. For supported wireless cards you could check out [Dortania's buying guide](https://dortania.github.io/Wireless-Buyers-Guide/). The type of network connection also doesn't matter as long as they're connected to the same network. My own setup is mixed with both wired and wirelessly connected Airplay bricks.

They broadcast their availability on your network like a Chromecast/etc do too. So if you can't see it you need to figure out why. I'd start with running a ping/traceroute to the IP of your Airplay device to verify you can actually route packets to it. Maybe it's firewalled or on a different subnet, or maybe your router doesn't route and/or forward all traffic (eg the packets that announce its presence) properly.

There are a lot of options to go by and I can't help you with this any more than I already did. I can't start giving some kind of general tech support here cuz then everybody will start opening issues and except me to help them. Been there, done that. It costs way too much time.

Please use Hackintosh or even Apple related forums or Reddit to get help if you n't sort it out yourself. There are plenty of people who will gladly help you to troubleshoot and help you step by step. This is not the right place for it though.

Good luck!
