### ISSUE TITLE
Optioned 9020

### ISSUE THREAD

**Issue by mbatrawi** [zearp/OptiHack#35]

**Comment by mbatrawi** [comment]
After sleep it will not wake up if sleep time more than 15 Min  and screen is black .
If sleep time less than 15 min it will wake up

**Comment by zearp** [comment]
Your screen may need the ```force-online``` option enabled in the frame buffer config. Try adding it there or edit the boot flags and add ```igfxonln=1``` there.

None of my screens need this option but it does seem to be needed on some screens. sine the options doesn't hurt I will add to the config. Let me know if it fixes it for you.

**Comment by zearp** [comment]
Your screen may need the ```force-online``` option enabled in the frame buffer config. Try adding it there or add ```igfxonln=1``` to the boot flags.

None of my screens need this option but it does seem to be needed on some screens. Since the option doesn't hurt, I will add to the config. Let me know if it fixes it for you.

**Comment by zearp** [comment]
Just added it to the config.

https://github.com/zearp/OptiHack/commit/9ad82c0deaf7af3da504cc0035572b356ff8a0f2

**Comment by mbatrawi** [comment]
not working

**Comment by zearp** [comment]
Maybe your screen goes in some kind of mode after that 15 minutes that macOS doesn't recognise. Check your monitor for any power saving options that you can toggle.

You can also try patching/adding EDID following [this](https://gist.github.com/ejdyksen/8302862) guide, it may help. Other than that I can't offer much help cuz I don't have/can't reproduce the issue on any of my screens.

You can also a debug build of WhateverGreen and see if there's anything in the logs that could help but that may be a long shot. I'm not certain the issue is actually caused by the EFI or any kexts.

**Comment by zearp** [comment]
Oh, one more thing that could influence it; the BIOS setting for iGPU/dGPU/Auto modes. Try experimenting with those, if set to iGPU now set it to Auto and vice versa. Good luck!

**Comment by mbatrawi** [comment]
I revert back to clover and Catalina and problem solved

**Comment by zearp** [comment]
Well that doesn't help anyone now does it.

**Comment by zearp** [comment]
Thanks for spamming the issues when you're not willing to contribute and solve issues. I'll just remove the issue. Pelse don't open any issues again.
