### ISSUE TITLE
Graphics setting in BIOS

### ISSUE THREAD

**Issue by Johnnyaker** [zearp/OptiHack#4]
When I leave the setting at Auto I cannot complete the install with my RX 570 graphics card. If I set it to AMD HD Graphics instead then the install works. Thought you might like to know about this. Auto works well when only using HD4600 graphics.

**Comment by zearp** [comment]
Did you remove the ```-wegnoegpu``` boot flag? Cuz that boot flag should disable the dGPU and everything should go via iGPU and then in post-install once everything works on the iGPU remove the flag and setup the dGPU.

I have no idea how the installer is even able to use the dGPU as it should be disabled. Very odd. Unfortunately I can't test this as I have no card that fit my SSF boxes. I need a short and low profile one.

**Comment by zearp** [comment]
Did you remove the -wegnoegpu boot flag? Cuz that boot flag should disable the dGPU and everything should go via iGPU and then in post-install once everything works on the iGPU remove the flag and setup the dGPU.

I have no idea how the installer is even able to use the dGPU as it should be disabled. Very odd. Unfortunately I can't test this as I have no card that fit my SFF boxes. I need a short and low profile one. Sorry.

**Comment by Johnnyaker** [comment]
I'll try it with the -wegnoegpu flag and see how it goes. Thanks.

**Comment by zearp** [comment]
Which config did you use? I had to double check but it's still in there on [here](https://github.com/zearp/OptiHack/blob/master/EFI/OC/config.plist#L520).

Either way, good to know about the BIOS setting. I will add that to the notes I think. Hope to get my hands on a nice dGPU soon. Hard to find a good deal on a passively cooled now profile card.

**Comment by GCPDetective** [comment]
@Johnnyaker If you are experiencing issues with Quartz Extreme with the dGPU after getting your first issue sorted out, I suggest you try disabling "Enable Legacy ROMS" in your BIOS as well.

**Comment by zearp** [comment]
Will sleep work properly with dGPU and legacy Roma disabled?

I really need to get a dGPU to test these things.

**Comment by zearp** [comment]
Did you test sleep with dGPU and legacy roms disabled?

**Comment by GCPDetective** [comment]
Sleep only worked the first couple times for me after doing a clean install for OpenCore. Hasn’t worked since. I haven’t really looked into that or hibernation yet as I don’t really use them and haven’t had time to check it out either.

**Comment by zearp** [comment]
I've had no problems with sleep at all. But I don't have a dGPU. I dunno if hibernate works properly, cuz I think the power led is supposed to turn amber when it's hibernating. Windows to Go can't do hibernation so I will have to do a full windows install on a disk. Will do when really bored.

I'd be curious to see your wake reasons, they're the key to getting sleep to work properly. At least on my side. Like the weird wake-ups coming from non-HID EHCx devices, that was sorted by re-introducing the EHCx_OFF patch. With hibernate I get wake-ups from RTC every 4 hours but with hibernations disabled it sleeps like a kitten.

When things stop working without anything changing I always get annoye cuz it reminds of Windows. Where a reboot fixes problems. That should not be needed in the *nix world. And macOS is essential as *BSD distro with a closed source window manager. It logs a lot, usually enough to find a cause and sort the problem.

But I get sleep is not important to some at all. My goal is to get everything to work like on a real Mac. Including exotic functionality. Normal sleep for me works good. I'm trying to get a hold of a dGPU so I can test these other things and also see if DRM can made to work easily.

**Comment by GCPDetective** [comment]
The auto generated system report that macOS generates whenever you log back in stated something about “wake reason: EFI” if I remember correctly. I believe the sleep issue may be because of the dGPU, more specifically AMD cards. Not sure why.

I actually still have Windows installed as well if you’d like me to test anything.

As far as DRM goes, I’ve been using the boot flag “shikigva=80” to fix it. I’ve only tested iTunes movies for now but I’ll also give some streaming sites a try later today as well.

This one is a little off topic but it seems like macOS will refuse to boot 90% of the time when the service pins are still shorted. Something with the IGPU, and it doesn’t matter whether there is a dGPU present or not. Windows doesn’t seem to have any issues. Don’t ask me how I know .__.

**Comment by zearp** [comment]
Yes, the service pins disable parts of the BIOS region so you can read/write to it. This changes the ACPI tables I think. In a way that macOS doesn't like at all.

Good to know about DRM not being that tricky. I was [reading up](https://github.com/acidanthera/bugtracker/issues/586) on the DRM+iGPU issues and it appears it's quite complex with signatures and what not. Thats why DRM works fine on my old Mac with iGPU but not on a more modern hackintosh.

**Comment by GCPDetective** [comment]
> I dunno if hibernate works properly, cuz I think the power led is supposed to turn amber when it's hibernating.

I just tested this and can confirm that the power LED is completely off in hibernation on Windows 10.

**Comment by zearp** [comment]
Thanks for testing! I wonder when the amber led is used. Maybe only for error reporting. I will check if I can get that kind of hibernation working. But it has no priority, just for the heck of I wanna see if it can work.

Today my Macbook didn't wake up the screen when connected to an external one. Seems there are some sleep issues in Catalina itself at the moment. Which is annoying when testing... any issues could be caused by the config or macOS itself haha.

**Comment by GCPDetective** [comment]
Yeah these Catalina bugs makes it all the more confusing in trying to track down whether the cause is the Hackintosh setup or the OS itself. Mainly one of the reasons I decided to downgrade back to Mojave for now as I was getting Finder hangs lol. Seems to be an issue with Catalina as other users running Catalina on authentic Apple hardware are having the same issues.
