### ISSUE TITLE
No video when reaching desktop

### ISSUE THREAD

**Issue by BrunoGM** [zearp/OptiHack#41]
More times than not, after finishing the boot in verbose mode the screen will just turn off instead of giving the login screen. I m using a (not DVI) DP to HDMI adapter. Any ideas on what the issue could be?

**Comment by BrunoGM** [comment]
Just found the note about the solutions for DP to HDMI adapter, gonna try them out.

**Comment by zearp** [comment]
DVI sounds like you're using a dGPU. It might be needed to add its port to the frame buffer config cuz it stays black.

Check out these two pages and if it doesn't seem too daunting go ahead and try it out.

1: https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html
2: https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html

Step one might be the only step needed.

When browsing for DP -> hdmi cables check the direction is right or is bi-directional.

The best connection for video is one without conversion, but not always an option. macOS doesn't like all conversion cables/dongles.

**Comment by BrunoGM** [comment]
Actually i m not using any dGPU, the video is coming from an HD4600 from a 4790k. Looks like the problem didn't happen anymore since I applied the patches you left on the tutorial tho, hope it is fixed. I ll keep you updated.

**Comment by zearp** [comment]
I hope so too!

Whats your exact model? Cuz I haven't seen any of these with a DVI output.

**Comment by BrunoGM** [comment]
Oh, My bad! It is Display Port to HDMI connector, not DVI, I don't know what i had in mind when i wrote that! Sorry for the mistake.
But it is a SFF 7020 with 2 display ports.

**Comment by zearp** [comment]
Ah haha, it happens! I have the same machines and can confirm not all DP -> hdmi cables will work. I have no glitches apart from one when it switches from text to graphical on start up. I think that can be prevented with some flag, I never considered it as something annoying enough to fix.

I'm using [this](https://www.amazon.co.uk/Braided-Connection-monitor-projector-Graphics-Grey/dp/B07QKYPSQ1) one, it should be for sale on most Amazon sites. I also had good luck with [these](https://www.ebay.co.uk/itm/Display-port-to-HDMI-Displayport-DP-to-HDMI-Cabl-video-hdmi-T5R6-A0E3-C6L0/402616688717) cheap adapter plugs.

If you can, enable screen sharing on your machine and the next time it boots into a black screen try to login to it using VNC from another device. It might just work, if it does check the current frame buffers settings in IOreg (the sections below the IGPU entry). I wonder what it will be show there and if there's any monitors connected and what type of connection they use.

The last few days we've been working on sorting out the connectors once and for all in an attempt to finish up all the frame buffer settings so that it works at 4k in Big Sur.

I added the ```force-online``` option that should fix this but maybe it doesn't work on all screens? I'm not really sure what exactly it does but does fix black screens for me on an AOC display. My Samsung display doesn't need any of it. It's kind of weird and there doesn't seem to be logic behind it.

Btw I'm not sure if macOS is to blame for some cables not functioning properly or that the ports themselves are picky and some cheap cables will add glitches since they lack shielding or don't make proper connections. Ideally run any display connections without any conversion. Use DP -> DP on the Dell for the best results.

**Comment by BrunoGM** [comment]
The problem is back...
The problem sometimes happen when I wake up from sleep too, actually.
I have no idea if my DP to HDMI cable is bidirectional, my cable looks like [this](https://www.ebay.co.uk/itm/Display-Port-DP-Male-to-HDMI-Female-Adapter-Converter-Dongle-Cable-PC-Monitor/323596510011?_trkparms=ispr%3D1&hash=item4b57dae33b:g:8WcAAOSwePReSKJD&amdata=enc%3AAQAFAAACgBaobrjLl8XobRIiIML1V4Imu%252Fn%252BzU5L90Z278x5ickk5v8gVt3hEWLVg%252F253w6XCYtR2PKg%252BSn4cI6BWJJq8sn9oatg%252FR1RMpkUnsPpYc1v5ejP4%252Fk%252B5P2fnft323XOWWix%252BMLff0s1YRSI6sGVZ0rTzpiPj3nWeZ9UW1ZgsNaObQvRFUVK2Fqqz8%252BkAqomoGxJv67KXmBFzzEHorbNR%252Fu51v77jjJbWGwPy6QoVUzRdBcQWEagIyTvzPMqlF0mU738R8MAy5abFityFnoBWfW2S84t%252FI%252FEwyMzS0vaulKw9N6alNsDnuOiaBPNrspAtNune8JlKWwxnRS9REFFtgt1iMEdiLHH8imsi54Ejoyx6na1MK4NRSWCQAgT1IhhTjNShi2KNFkWnvqPSJAMEry4ayKVdtd7ggl3AXaooDvkiORBPeZHFz5VrVm0b0KAHeC6AfPXODSOfU5Xsy1CT7fpc%252FnAzEhi7cPK8gUVr8ptd2O182OI9y79qKD7B6p5Hk2HXXz9thY7fbme01Ggi3X91so8bwHL0Eh2%252Bp0jtCaOSXSbbVCG1BEwD4lJgv1fx80j6o2fkgFjDl4cQtLx1ogRgTVwz9cG1feum5XiJOIAqjngVSq923TKw18a2%252BDXi1iRlj7ht0JtBfSNzMKC%252FgwSimGX6k7zoI6Jf6ElzRhoLfuEyPfvqFK8x8A5Jhw3RTHTI%252FO%252FefN2FhoJuhCmsyBK%252FH3FxLYlsJxjtnhBYdfI4JP0SlH%252BC70D63qJNoGUcWXnMmTj3ydtawOrqLKIGLND8IvZXKbbzVzTZOKhhYaln%252FERgGp8V72OTx9gzxP8F%252BaIeMT0RTXuFEqHI%252BU1HFA%253D%7Ccksum%3A3235965100111c0e473dffe242cc928d4c67a4ff9b03%7Campid%3APL_CLK%7Cclp%3A2334524). But if the problem only happens a few times maybe its not the cable? Since when i have video, i can have it on for a week without glitches...
PS: I have a LG monitor.

**Comment by zearp** [comment]
If the problem can’t be reproduced reliably it’s hard to solve it. If not impossible as it could be caused by a lot of factors. Nothing changes in your hard and software setup yet you get different results from the same actions.
