### ISSUE TITLE
Black screen when using dual monitor

### ISSUE THREAD

**Issue by binhnt12** [zearp/OptiHack#42]
I install Catalina on my system: Optiplex 9020, intel hd 4600. Everything work well but have black screen error when I using dual monitor (not 4k), I use DP -> HDMI cable for both monitor. I follow with Installation Index (BIOS settings, Download and create the installer, Copy EFI folder,...) except Post install, and I also follow Graphical boot. I only test for using dual monitor.
What solution for me or did I miss something?
Thank all!

**Comment by zearp** [comment]
I don’t know why you get this result but I’m pretty certain it isn’t caused by the EFI. You’ll have to do some trouble shooting to find out the cause. Switch ports, displays, cables. Make sure both screens can work stand alone. Try different cables. Where possible use DisplayPort to DisplayPort only. If your screen supports it it’s best to use DisplayPort. 

I use DisplayPort to hdmi cables and have no issues using dual screen. So I’m quite certain your issue isn’t caused by the EFI. Issues are not really meant for support but merely for reporting bugs and errors caused by the EFI.

In some older issue someone solve their issue with a different cable. There’s not much I can do as it’s not caused by the EFI, or software for that matter. Good luck and keep me posted on any progress or fix.
