### ISSUE TITLE
Monterey Beta 2

### ISSUE THREAD

**Issue by davidAlaBer** [zearp/OptiHack#48]
The system preferences asks for updates and download Beta2

When rebooting Opencore picker shows a new entry 'Macintosh HD' but never installs  the beta2 Boots normally and asks for update again. The process repeats.

Where is the problem?

Hackintool says I am in Big Sur by the way (I am in Beta1) 
![image](https://user-images.githubusercontent.com/34654112/123806614-651b3f80-d8ef-11eb-96f4-73c39b2d8123.png)

**Comment by zearp** [comment]
Thats a very weird result you got. That build number is for beta 1 and your macOS version should be 12.x for Monterey and 11.x for Big Sur yet you have 10.16. Something is not right. Can you post the full EFI that results in this?

Do you have the latest Hackintool installed? Maybe it needs an update cuz on my beta 1 it looks fine:

![Screen Shot 2021-06-29 at 16 23 24](https://user-images.githubusercontent.com/63272687/123815708-fcd05c00-d8f6-11eb-9295-34a94a8716d8.png)

Also I suggest not to do any of this testing in macOS beta anymore. It is just too tricky and hard to rule out things cuz we don't know what's caused by the beta and what's caused by other things. You're of course free to play with the beta but I can't really help out much since your config is different for mine, I don't have dGPU or additional hardware other than Airport cards in some of them. Most are 100% stock using ethernet.

**Comment by davidAlaBer** [comment]
Hi, My hackintool is updated.
About Mac Os shows Monterrey, not hackintool.
Funny!
Othe funny behaviour is that always after I reboot a message warning appear saying  I shutdown the system because of a problem but I shutdown/reboot from finder menu. JFYTK.

**Comment by zearp** [comment]
Without seeing the full EFI that results in this I can't do anything.

**Comment by davidAlaBer** [comment]
Reinstalled Hackintool, now it shows the right info. Thanks!

**Comment by davidAlaBer** [comment]
[EFI.zip](https://github.com/zearp/OptiHack/files/6734498/EFI.zip)

Beta2 doesn't install

**Comment by zearp** [comment]
Thats good. I'll consider this issue as solved cuz I dunno why the beta doesn't install for you. Maybe it's a bug in the beta. I can't really support anything to beta macOS unless the machine is exactly the same as mine, which is stock. Else it's just too tricky to troubleshoot. If I can test things myself its not an issue but I don't have the parts to match my h/w to yours so it will require me writing long posts and I simply don't have the time for that right now. Maybe on the weekend again. Sorry.

**Comment by davidAlaBer** [comment]
No problem! Thanks. No Beta 2 but the machine is working for the moment.

**Comment by zearp** [comment]
The beta 2 (21A5268h) updater panics due to SMC issues. This could be a bug or might require VirtualSMC to be updated. I tried booting into it with compatibility checks disabled and also a few variants of SecureBootModel and also with VirtualSMC flags but can't get passed the panic. The full installer might work, installing macOS on top of the same or an earlier macOS version will simply upgrade it and keep all apps/settings. It can also work for downgrading but YMMV there. I haven't tried with a full installer yet but it can be downloaded [here](http://swcdn.apple.com/content/downloads/54/23/071-59953-A_U9D4NB05NR/nqzt71pnylsuux326a4vqexb33oz0auhas/InstallAssistant.pkg).

**Comment by davidAlaBer** [comment]
I am going to give it a try to the installer you provide.

**Comment by davidAlaBer** [comment]
Downloaded and run the installer. It leaves things like the were before. no changes. no bad news :)
Is it beta 2 installer? Running updater yet just in case...

**Comment by zearp** [comment]
Yes, it is the beta 2 installer inside the package. You run it and it will put ```Install macOS Monterey beta.app``` in /Applications.

**Comment by zearp** [comment]
Yes, it is the beta 2 installer inside the package. You run it and it will put Install macOS Monterey beta.app in /Applications. Then you can make install usb using the createinstallmedia script or run the installer directly.

**Comment by davidAlaBer** [comment]
Yes, i run it but no beta 2 installation. There is a installer registry. I will take a look at it. But dont know what can be a clue... there are a bunch of error lines!

**Comment by davidAlaBer** [comment]
![image](https://user-images.githubusercontent.com/34654112/123865750-97975d80-d92c-11eb-80f7-0f01a62f31cf.jpeg)

**Comment by davidAlaBer** [comment]
I am trying to install from recovery partition. Lets see!

**Comment by davidAlaBer** [comment]
![image](https://user-images.githubusercontent.com/34654112/123865964-d1686400-d92c-11eb-94a9-9b249883d57f.jpeg)

**Comment by zearp** [comment]
> Yes, i run it but no beta 2 installation. There is a installer registry. I will take a look at it. But dont know what can be a clue... there are a bunch of error lines!

The app you posted a screenshot of is the beta 2 installer, the beta 1 installer didn't have the name Monterey in it. It was just called Install macOS 12 beta or something like that.

**Comment by zearp** [comment]
Using the full installer results in the same issue and additionally makes it not possible to boot back into the previous version. the fix is to boot up the beta 1 installer and install beta 1 on top of it again. I think we'll have to wait for VirtualSMC updates or something else. I really don't know. Beta 1 was good, but beta 2 seems rather broken for us. Normally I wait until public beta's so the worst bugs are gone. These are still developer beta's.

**Comment by zearp** [comment]
Using the full installer results in the same issue and additionally makes it not possible to boot back into the previous version. The fix is to boot up the beta 1 installer and install beta 1 on top of it again. I think we'll have to wait for VirtualSMC updates or something else. I really don't know. Beta 1 was good, but beta 2 seems rather broken for us. Normally I wait until public beta's so the worst bugs are gone. These are still developer beta's.

**Comment by davidAlaBer** [comment]
Bad :(
Now I am stucked in Beta 2 installer on Boot. Cant get to the desktop.

I have a mechanical disk with catalina in the opencore picker. What do you recommend?. I dont mind to go back to Catalina. How can I do it?

**Comment by zearp** [comment]
I posted above how to fix it without losing any data, settings or apps. Use the beta 1 installer usb stick to install Monterey beta 1 on top of beta 2 and after a few reboots it will be ok again. Beta 2 is too broken. I'm not going to put in any more time and wait for next beta version. I'm sure other people will also run into this too. It's expected with beta's that at some point something will break.

Pay good attention to the picker menu when it's installing and rebooting, it doesn't always auto select the right entry. It took about 30 minutes to install beta 1 on top of beta 2 on my test machine. Bunch of reboots and a few times booting into the wrong thing when I didn't pay attention to the picker menu.

I recommend using spinning disks only for bulk data, running an OS from a spinning disk is too slow. For playing around I'd recommend a nice fast usb 3 stick. Ones with fast enough read/write speeds to run an OS without wanting to smash the keyboard. macOS can be installed to pretty much anything, including usb sticks and even sd cards. And boot from it too.

**Comment by davidAlaBer** [comment]
![image](https://user-images.githubusercontent.com/34654112/123875675-632a9e00-d93a-11eb-995a-dda3d152b378.jpeg)

**Comment by zearp** [comment]
I'm getting the exact same SMC error on my NUCs. Beta 1 was fine there, nothing in the EFI changed. These are just bugs and/or require updated kexts. I don't expect anything soon cuz developers of the kexts might also wait and see what's gonna change next instead of putting in time now they can't get back when Apple changes it's mind again. It's just not worth putting too much time in beta's unless you wanna learn and don't mind reinstalling and playing around. 

But for me the beta chapter is closed as far as supporting it on Github goes. Who knows what the next beta fixes or breaks. It's not worth going trough all the troubleshooting ever 7-14 days until Monterey is released in a few months. I will keep trying the new beta's on my test machine but it won't get anywhere near daily driving until maybe 12.3 is out.

I don't know what you mean by posting just an image. The first time you boot into the installer it will copy all it needs to the internal disk, from there on out you need to make sure it keeps booting into the internal disk and the correct partition, it will be named macOS Installer or something after the first step. After a few reboots it will rename itself to whatever name you gave the drive. Then it should be done.

**Comment by davidAlaBer** [comment]
Good ;) Typing from Beta 1 desktop. Remember guys Beta 1 and @zearp are awesome. Stay with them!

**Comment by zearp** [comment]
Beta 2 now works, use attached EFI or clone the repo and edit the config and set ```SecureBootModel``` to ```Disabled```. I upgraded using the full installer app and clean install too. Did not test App Store update. Wipe nvram before installing/booting into the installer.

![Screen Shot 2021-07-04 at 08 09 05](https://user-images.githubusercontent.com/63272687/124374925-635ecc80-dc9f-11eb-87a4-ba17b68864f5.png)

[EFI.zip](https://github.com/zearp/OptiHack/files/6759448/EFI.zip)

**Comment by davidAlaBer** [comment]
I will give it a try soon!

**Comment by davidAlaBer** [comment]
Hi!,
1. I download the repo, edit config (disable SecurebootModel), serial... , and replace EFI (except usbports.kext).
2. Download the Beta 2 app installer and install (from the desktop?)
3. When reboot I reset NVRam and cross my fingers.

¿is it correct?

**Comment by zearp** [comment]
The important bit is that ```SecureBootModel``` must be disabled _before_ running or booting into the beta 2 installer. Wiping nvram is just for good measure as lot of settings and stuff is kept in there. I've upgraded my beta 1 to beta 2 and also did a clean install both went ok.

- Make config changes, reboot and reset nvram
- Run installer or boot into it if you made a full installer usb
- Install

Mind you beta 2 has a very annoying bug in Safari where the tab previews don't disappear properly causing the webpage not to see you click or scroll until you hover of the tabs to make the preview go away. Also the weather widget is broken unless you do a clean install.

Beta 1 was better imho. Beta 3 should be out next week.

I'm not sure what you mean with USBPorts.kext, I would download the latest release from the repo and use that as base. Then just apply any changes you need for your setup and it should be fine. For USBPorts.kext the only thing that matters is that the SMBIOS you use matches the one in the plist inside that kext. If it doesn't match weird usb things happen. As I wrote in the readme editing lines 25 and 182 is enough.

**Comment by zearp** [comment]
The important bit is that ```SecureBootModel``` must be disabled _before_ running or booting into the beta 2 installer. Wiping nvram is just for good measure as lot of settings and stuff is kept in there. I've upgraded my beta 1 to beta 2 and also did a clean install both went ok.

- Make config changes, reboot and reset nvram
- Run installer or boot into it if you made a full installer usb
- Install

Mind you beta 2 has a very annoying bug in Safari where the tab previews don't disappear properly causing the webpage not to see you click or scroll until you hover over the tabs to make the preview go away. Also the weather widget is broken unless you do a clean install.

Beta 1 was better imho. Beta 3 should be out next week.

I'm not sure what you mean with USBPorts.kext, I would download the latest release from the repo and use that as base. Then just apply any changes you need for your setup and it should be fine. For USBPorts.kext the only thing that matters is that the SMBIOS you use matches the one in the plist inside that kext. If it doesn't match weird usb things happen. As I wrote in the readme editing lines 25 and 182 is enough.

**Comment by davidAlaBer** [comment]
About usbports. I mapped my ports for the 9020. If I replace my kext, will the mapped be lost?

Enviado desde mi iPhone

**Comment by zearp** [comment]
Edit the plist inside your kext file to match SMBIOS model and you should be fine. That's all the really matters in there.

I was thinking of using a different method where the model isn't used at all but it makes the EFI a bit more bloated. Editing two lines isn't the end of the world and if you forget you'll surely notice cuz usb and sleep will behave weirdly.

I think the 9020 and 7020 have the same map except for internal headers, but not all models have those. The smallest form factor ones only have external usb ports.

**Comment by mgrimace** [comment]
I'm just catching up on all this now, thanks @zearp for all your work and testing here. I'm on Catalina still on the previous SMBIOS. Can I clarify: do I need to generate a new USB port map after updating the SMBIOS (and generating new serials, etc.)? Typically what I've been doing is copying my old port map usb kext with each new successive EFI update. I'm going to hold of testing Monterey at the moment, I need my monitors (4k) to work reliably and this has become my primary working machine but I may take the dive if I need a distraction over the summer :)

**Comment by zearp** [comment]
@mgrimace You can use the map you made if you edit the 2 lines containing the SMBIOS model and adjust it to match the new one. Nothing else is needed other than serials matching the SMBIOS used.

There's a way to map the ports without the need for a model but it relies on USBInjectAll + ACPI map which I rather not use that as it adds another file and also isn't stateless. The USBPorts.kext is stateless, it just has a plist inside and thats it. Hackintool exports them both. It also allows to "import" a USBPorts.kext and export it again if you wanna try the other method. Both result in the same.

It also possible to run Monterey using any other SMBIOS but it will require either patching the installer and/or running with compatibility checks disabled. Not ideal. The Mac mini 7,1 one supports Monterey is as far as I know the only Haswell platform getting Monterey.

I use some 7020's as "cluster" of workstations and they been behaving well with the new SMBIOS on Catalina, Big Sur and Monterey. The higher iGPI base clock doesn't seem to impact anything. I am looking into adjusting the base click back to somewhere between 200-350mhz but thats not really a priority. You can of course use whatever SMBIOS suits your needs best. My main 7020 will remain on iMac 14,3 and Catalina for a long time. It's just proven to be super stable and reliable and a great fall back just in case I break something elsewhere.

In my limited testing Monterey feels a lot more snappy than Big Sur. But maybe thats just my anti-Big Sur bias lol. Catalina is still my preferred macOS though. It's stable, matured and has a compact design that isn't wasting space and many things that need 2-3 clicks in Big Sur and Monterey only need 1 click in Catalina. Minor for some, big if these things are part of your workflow. Having to spend a few more seconds/clicks to do the same in Big Sure/Monterey vs Catalina will add up.

**Comment by zearp** [comment]
As for 4k, I tested it in Monterey with the current EFI and it seemed to work using a new 4k DP to hdmi converter plug. I still haven't found a DP dummy that does 4k so results might not be accurate but it seems to work!

![122439676-2656c280-cf9c-11eb-83ba-be91899dec03](https://user-images.githubusercontent.com/63272687/124605485-3e6b8480-de6c-11eb-9c5f-d4097e83806f.png)

**Comment by zearp** [comment]
As for easy of testing, I ordered some more of these and they are such a time and life saver.

![611Elj1FuJS _AC_SL1300_](https://user-images.githubusercontent.com/63272687/124606101-db2e2200-de6c-11eb-9b22-084851db96e1.jpg)

I use these things all the time for bootable backups and testing stuff, doing clean installs, etc etc. They're only $5 a piece for a good one that has UASP. Worth their weight in gold really. SuperDuper can make bootable backups of Monterey if you let it wipe the destination the first time, afterwards you can use smart update.

So if you got one of these or an old disk caddy clone your install to one, then update your install to Monterey once its in public beta (I wouldn't use it as daily driver now) to see how things behave. If its bad just boot form your backup and clone it back to your internal disk. Or do it the other way around haha.

**Comment by mgrimace** [comment]
> @mgrimace You can use the map you made if you edit the 2 lines containing the SMBIOS model and adjust it to match the new one. Nothing else is needed other than serials matching the SMBIOS used.

Thanks, I did this (replaced the SMBIOS model in the old kext with Macmini7,1). That seems the easier route and agree re. avoiding the model-less option that adds more files/complexity. That reminds me I had designated a USB port as "internal" on my SFF (with no actual internal header) since I routed my Fenvi's BT usb cable to an external port but wanted it to function normally.

Going to update the EFI/serials today!

> As for 4k, I tested it in Monterey with the current EFI and it seemed to work using a new 4k DP to hdmi converter plug. I still haven't found a DP dummy that does 4k so results might not be accurate but it seems to work!

Well this is intriguing! Maybe I will take the plunge on the beta after all (after a good backup)! If/when I do test this out, I'll report back with my findings (no ETA though).

**Comment by zearp** [comment]
> That reminds me I had designated a USB port as "internal" on my SFF (with no actual internal header) since I routed my Fenvi's BT usb cable to an external port but wanted it to function normally.

I'm doing the same, many times I forgot to set the port back to 255 and then wonder why sleep is not working. It does the instant wake thing with my Airport cards when the port it connects to isn't set to 255. I haven't used any Fenvi cards, does HID proxy work on those?

For beta 2 don't forget to set ```SecureBootModel``` to disabled, else you will get stuck in a reboot loop in the 2nd install stage. This didn't happen with beta 1.

Speaking of secure boot stuff, I'm experimenting with real secure boot on my NUCs as we can 'sign' OpenCore and boot with secure boot enabled in the bios. The issue for the Dells is that in order to enable secure boot in the bios we must disable loading of legacy roms which in turn breaks sleep. It would be fun to sort that out but surely not a priority at all. Just nice if we could get it to work on Dell too.

**Comment by davidAlaBer** [comment]
<img width="575" alt="Captura de pantalla 2021-07-06 a las 17 20 36" src="https://user-images.githubusercontent.com/34654112/124625937-872c3900-de7e-11eb-9826-07975167098a.png">
Beta 2 installed :) a Mac mini with a huge Rx 570, my boot time is now 45 secs I guess wrong usbports.kext wrong SMBIOS was the issue.

**Comment by zearp** [comment]
You can't just enable UEFI Secure Boot in the bios without signing parts of OpenCore yourself.

Check out this section of the OpenCore manual: https://dortania.github.io/docs/latest/Configuration.html#x1-840002

There is a Dortania guide in the making covering this in more detail.

**Comment by davidAlaBer** [comment]
I wil take a look about 'signing'.

Usbports remapping was neccesary after installing beta 2 and updating smbios in the kext because i lost internal usb port. Now everything works!

**Comment by zearp** [comment]
If you used your working USBPorts.kext with the internal ports mapped and only changed the model in the plist those ports shouldn't disappear. Are they still in the plist but not visible? That would be super weird. Maybe you forgot to migrate your own map?

The map I provide only has external ports as my machines are all SFF that don't have the port.

You might also push over the 15 port limit with the internal ones mapped. That can also result in very weird issues. Make sure you map 15 or less ports. Disable 1-2 ports on the back you don't use if you're over 15 with your internal ports mapped.

**Comment by zearp** [comment]
What a dumbs I was wasting so much time on issues all opened by you. Should close issues all together. I'm not a help desk.
