### ISSUE TITLE
Recovery Drive Fails to Boot to Picker When Using HfsPlus.efi

### ISSUE THREAD

**Issue by ghost** [zearp/OptiHack#52]
When attempting to install onto a 7020 flashed with the latest BIOS and the default (+ UEFI) BIOS settings, the system will not boot to the picker when using HfsPlus.efi. 
If HfsPlus is swapped out with OpenHfsPlus.efi from the OpenCore release (and the plist is edited), it will load, but will then boot loop when attempting to load the installer (which I'm guessing is due to the swap).
I've followed all of the directions from both the old and new installation guides, tried multiple installer layouts (App Store installer, GibMacOS installer, the installer recommended on the Dortania guide) attempted to follow the Dortania troubleshooting guide; nothing seems to work. 

I'd submit logs, but none are generated when it freezes this early in the boot process.

**Comment by zearp** [comment]
I'm a bit confused by what exactly is happening. What do you mean with recovery drive? Can you get into the picker at all? Will not boot, can you expand on that? Do you see the macOS installer in the menu when using OpenHfsPlus? What happens when you boot into it?

Sounds like a file corruption or EFI partition issue to me. You can test it by formatting an old small usb stick as FAT32 and put the EFI folder from the repo on there, then try booting from that using the F12 menu. You should at the very least get into the picker, it is also required to get in there to change the required UEFI settings so I assume you got that far but it is not clear to me.

That boot loop shouldn't happen. The driver is very basic in what it does, allows you to see and boot into HFS+ partitions from the picker. It doesn't do anything more than that. 

```
MD5 (HfsPlus.efi) = 62ecb4b7a60b4c71728370d9ee74b3b1
```

You can also check if yours matches this. I am 100% certain this file works cuz I use it synced to the repo on my own machines and did a clean install just the other day when Monterey beta 3 came out.

My first instinct would be to redo the EFI partitions and as sanity check do the FAT32 thing.

**Comment by ghost** [comment]
I'm sorry; I wasn't specific enough when creating the original post:

I am attempting to perform a clean install onto a blank hard drive on an Optiplex 7020. When I attempt to boot from the flash drive, I reach a black screen. 

It seems that HfsPlus may have been a red herring I stumbled onto while making other changes- I seem to be only able to reach the picker when swapping out Bootx64.efi, OpenRuntime.efi, and OpenCore.efi with their equivalent troubleshooting files (which  work with both OpenHfsPlus and HfsPlus).

The EFI sanity check resulted in the same issue- a black screen after POST but before the picker.

**Comment by zearp** [comment]
Very weird! Can you check inside your case if there's a sticker with a number on it somewhere? It's usually on the inside of the lid. Also check if your bios is versions A18.

I've also published a new release, it would be great if you can try that, also in case I need to reproduce something here its good we use the same version.

Only make modifications to the config file, don't add/change any kexts and let me know if you made any config changes that aren't serials/etc.

**Comment by ghost** [comment]
I tried the new build and received the same results; no modifications to the config aside from the serials from gensmbios and the ROM.
The computer is on BIOS A18.

The lid does have a sticker on it:
"AMT_DASH_VPRO: DEFAULT

1

DELL LBL P/N TY130"

**Comment by zearp** [comment]
Thats the good number to have yeah. I really don't know what goes wrong for you. Maybe you're forgetting some steps or something is actually broken in your machine, really don't know. I need to know exactly what you're doing and where it's going wrong. It is unclear to me still.

If you follow the guide it would just work. Maybe you forgot some step like loading bios defaults, or some UEFI offsets. I don't know if you can see the OpenCore picker or what happens when you boot into that. Verbose boot is enabled and getting into the picker should be trivial using FAT32 method.

If you can't boot from the FAT32 stick with an EFI folder created and the BOOT/OC folders inside those then I would say UEFI is not enabled in the bios. Booting UEFI is a lot easier than anything else cuz all it requires is a FAT32 formatted filesystem and an EFI folder with a BOOT folder inside that loads up the rest from the OC folder.

If I were you I would focus on being able to boot the repo's EFI folder from a FAT32 formatted stick. Once that works you can use that stick to boot into the installer stick if you made on already. After the first step of the install you don't need the installer anymore cuz it copies everything to the disk and keep using the FAT32 stick to boot until installation is complete.

Either way, I'm going to need a lot more details, like step by step of what you're doing and what the result on the machine is. Something is missing on your end, it is easy to miss steps when starting out with this. Take it slow and double check things. If the current EFI Was broken in such a way its not possible to boot into the OpenCore picker at all I would've seen more issues and also run into it myself.

This is not a dig at you but good news cuz there's probably something you overlooked or forgot that is causing this. It is just very hard to figure that out remotely for me.
