### ISSUE TITLE
9020 usff i7

### ISSUE THREAD

**Issue by davidAlaBer** [zearp/OptiHack#54]
Hi!
After learning a lot and having a 9020 mt running Monterey I want to share that  I had the opportunity to buy a 9020 USFF. What do you recommend to start with?
Does it share something in common with 7020/9020 sff or mt?

I found a guide in github for this machine except for the proccesor (i5 instead i7).

What about wifi/bt options? Broadcom Pci or a cheap usb dongle?

And dp>hdmi adapter or a dp>hdmi cable?

It would be great to have your feedback on this project. I plan to use it connected to my tv most of the time.

Thanks!

**Comment by zearp** [comment]
The USFF is the same platform but with some things removed to make it fit (no pci-e slots, less usb ports, less ram slots, etc). You can try the current EFI but you would have to replace the usb map with one made on the machine (can be done in windows too). Other than that it will need a different audio layout as it lacks some audio ports as well. Layout id 15 should work I think. The smallest models do have a different platform/chipset 9020m but will also work with some modifications.

Differences: https://i.dell.com/sites/doccontent/shared-content/data-sheets/en/Documents/optiplex-9020-micro-technical-spec-sheet.pdf

For the rest you can check the Dortania buying guides for what's compatible. I wouldn't use any wifi dongles as the y'all require 3rd party drivers and software to work and connect, it doesn't integrate with macOS. A cheap bluetooth dongle is an option if you don't need anything other than basic bluetooth (mouse/keyboard/audio).

Anything that converts DP to hdmi is subject to YMMV. I have cables that work fine on one machine and not on another. The combination of machine + cable + screen matters for macOS. Best to use DP -> DP.

That just a quick summation. I can't really start helping out with things unrelated to the core 7020/9020 stuff other than what I covered on my repo's already. There are simply too many cards and things to get too detailed. My goal is to provide a stable and fully functional EFI to get the base model up and running. Any additional hardware is really up to the user to get going.

I can really only provide basic info anyways because there are simply too many different cards to support, both dGPU. wifi/bt combo and other pci-e cards people may use (NVMe/etc). Though even for NVMe I made a bios hacking guide but thats not for the faint of heart.

My thoughts on wifi/bt are on my NUC repo: https://github.com/zearp/Nucintosh#apple3rd-party-bluetooth-and-wifi -- it also applies for any other machine but instead of a m.2 converter board you get a pci-e one.

For anything more detailed or in depth there are much better places like the Dortania buying guides and forums/etc.

Good luck!

**Comment by davidAlaBer** [comment]
Hi!
Fabulous progress in my 9020 USFF. Catalina install working and updated to Big Sur.

I wasn't able to make Bluetooth work (wifi works)
BCM94360HMB (AW-CB160H) wifi+bt combo
What do I need to make it work? any patch needed? how to proceed?

Thanks for your advice

**Comment by zearp** [comment]
What exactly did you try to get it to work?

**Comment by zearp** [comment]
- How did you connect the usb headers from the wifi/bt combo card? To an internal usb port or one on the back?
- Did you map the usb port it connects to as internal? This shouldn't be needed make it work but is needed for sleep
- What kexts are you using if any for the card, it is not native so will need kexts/drivers. Your card needs [this](https://github.com/acidanthera/AirportBrcmFixup/releases) ands [this](https://github.com/acidanthera/BrcmPatchRAM/releases).

Please also be aware this is not a general support forum. This card is widely used and there are many guides on it. The repo issues should only be used for issues relating to the EFI not as a help desk.

**Comment by davidAlaBer** [comment]
Firstly I installed your EFI as it is and I got wifi working but not bluetooth.
Hackintool says fw is not installed, so I found PCI number and added entries for Brcm patch kext and injector. When I  reboot it stops in the middle and I need to boot from the installer and erase it.

**Comment by davidAlaBer** [comment]
How did you connect the usb headers from the wifi/bt combo card? To an internal usb port or one on the back?
> mini pci e card with 3 antennas (internal)
Did you map the usb port it connects to as internal? This shouldn't be needed make it work but is needed for sleep
>It is a pcie, I dont understand...
What kexts are you using if any for the card, it is not native so will need kexts/drivers. Your card needs this ands this.
> Yes; I use them and read your NUC experience about it.

What makes no sense for me is that I cant boot to the desktop... there must be any inconvenience or bad config. Funny I found [another EFI in Github](https://github.com/Lorys89/DELL_OPTIPLEX_9020_USFF) for this 9020 model USFF and BT works with it but Hdmi has an strange behaviour (glitches) and I guess it is not as optimized as yours in display and ports. Would you mind to take a look at it? Also maybe you can add some conclusions for complete your guide and for 9020 models, MT, sff works well, only usff has

**Comment by zearp** [comment]
The wireless part is pci-e and the bluetooth part is usb. Hence a cable coming of the card going to either an internal usb header or a port on the outside. That port must in the map to work at all, and must be set to internal (type 255) for sleep to work properly.

Pretty sure all you need to do is setup the two kexts I linked and make a new usb map or use the one on the other repo you found as that one has an internal port mapped. Don't add the missing port from the map you found to the map I made cuz it uses different methods of setting up and merging the ports inside macOS. Use the full USBPorts.kext on the repo you found or make a new map from scratch.

This port is missing form the map in the EFI: https://github.com/Lorys89/DELL_OPTIPLEX_9020_USFF/blob/main/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L121-L131

You do not have to setup any devices in the config, this is only needed if you want to change options that can't be done via boot arguments or if you like having it there. Maybe you make a mistake adding which causes boot to fail, I don't know. But I do know this is well outside the scope of the repo and not an issues caused by the EFI's default config.

I don't have any 9020 or 7020 models with an internal usb header. I only have SFF boxes that all miss the internal header. Like the guide says if you use internal usb headers you need to make a new usb map. I can't manually add internal headers to the usb map because I can't be sure its working properly and it might also bump the map over 15 ports.

There is nothing to add to the guide in regards to this, it is already mentioned you need to make a new map if you end up using internal usb headers. But you are free to open a PR with any improvements or fixes.

**Comment by davidAlaBer** [comment]
I make a quick try with your advice and still no boot, it just stops for long time. Probably some fine tuning for the kext is needed, I will try soon properly.
Thanks!.

**Comment by zearp** [comment]
I’m just wasting my time here. You cant be bothered to provide a tiny bit of info I ask for in templates or replies and you keep opening issues for things you could Google. Like how to setup this card. But instead you open an issue.
