### ISSUE TITLE
Not an issue, just don't know where to put this.

### ISSUE THREAD

**Issue by GCPDetective** [zearp/OptiHack#55]
Hey what's up man, I know you said no donations last time I asked about a year ago but I'd like to make one anyways. You have no idea how much of a help this has been especially with the transition to Monterey now. Thanks for all you guys do!

p.s. I won't take no as an answer this time lol

**Comment by zearp** [comment]
Thank you but for me money and Hackintosh don't go together. I'm happy to hear it has been useful for you though. 

Hopefully we can sort out 4k once and for all and then the build is pretty much as good as it can get. I've skipped Big Sur myself mainly due to Preview being so bad and I use that quite a lot. Some software can be unstable on Monterey but I personally didn't have issues with crashing apps so far. Even the free (for Mac users) Fusion VMware works flawlessly on it.
