### ISSUE TITLE
Does labeling a USB connector correctly matter?

### ISSUE THREAD

**Issue by GCPDetective** [zearp/OptiHack#63]
Decided to tinker around with Hackintool on my MacBook Pro just to compare things with my Optiplex and noticed that the MacBook Pro has all connectors (except the two internal ones) labeled as USB3, even ones that are used for USB2 backward compatibility. I confirmed this with two different USB2 and USB3 devices. Wondering if this was a simple mistake on Apple's part or is there a benefit to it and maybe doing the same to the Optiplex?

**Comment by GCPDetective** [comment]
<img width="768" alt="Screen Shot 2021-09-29 at 2 11 20 AM" src="https://user-images.githubusercontent.com/56003049/135212728-bb770876-80f8-4948-b2c1-4169d13e584a.png">

**Comment by zearp** [comment]
Those are so called companion ports. A port that is both usb2 and usb3 is labeled as usb3. I've done the same not not ago. It doesn't seem to matter at all how they are setup but setting up the companion ports can't hurt and Appel does it too.

https://github.com/zearp/OptiHack/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist

**Comment by zearp** [comment]
Looks like I only setup the ones on the front in the port map. Might fix that when making the move to Monterey as default once it's released.

**Comment by zearp** [comment]
Those are so called companion ports. A port that is both usb2 and usb3 is labeled as usb3. I've done the same not long ago. It doesn't seem to matter at all how they are setup but setting up the companion ports can't hurt and Apple does it too.

https://github.com/zearp/OptiHack/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist

HS01, HS02, HS09 and HS10 are all setup as usb 3 since they are combined usb2/3 ports.

**Comment by GCPDetective** [comment]
Gotcha. I still have HS01, HS02, HS09 and HS10 labeled as USB2 😂. I only have SS01-SS06 labeled as USB3. Like you said probably not an issue but going to fix it anyways as soon as I get home.

Also just to clarify, companion ports are a set of HSXX and SSXX sharing the same physical port right?

EDIT: Forgot to mention that the USB Map section of the OptiHack guide says to label all HSXX ports as USB2.

**Comment by GCPDetective** [comment]
Forgot to mention that the USB Map section of the OptiHack guide says to label all HSXX ports as USB2

**Comment by zearp** [comment]
Good catch, I need to update that part. Yes, same connector. I have not noticed any differences and never really encounter any usb issues as well. Even with hubs and many things connected it has all been good.

**Comment by GCPDetective** [comment]
Are you using Big Sur or Monterey as your daily right now? And do you have any issues with usb storage device disconnecting and reconnecting randomly? It would disconnect either in the middle of a big file transfer or about once every hour when it's connected but idle. I was thinking the usb storage device was going bad but it works fine on my MacBook Pro.

I started noticing it downgrading back to Big Sur, so I'm not sure if it's because of the latest Big Sur update that came out or the latest EFI pack I updated to before the downgrade. Going to try swapping EFI with an older version and seeing if that may be the issue. If not, then back to Monterey I go lol.

**Comment by zearp** [comment]
I'm still on Catalina for daily driving but my test machine is on Monterey. I haven used Big Sur at all. There are too many design failures for me, mainly Preview when reading documents is very bad in Big Sur it is a lot better in Monterey. This is all subjective of course but I've skipped Big Sur for personal use.

I have no problems with devices disconnecting randomly. I have some external disks always connected for Time Machine and VMs. Even with lots of sleep cycles they remain connected including one that uses encryption. It works exactly like on my real Macs. 

One thing to keep in mind is macOS usb 15 port limit. Once you go above it weird things can happen, such as devices being disconnected when a new usb device is found. It shouldn't be an issue when not using a dock or hub. I would check the logs the moment it happens it may reveal why it was disconnected.

I hope Monterey GM will be released soon because the beta's sometimes require a fresh install/upgrade using usb installer  instead of simply updating from the App Store. I consider this a bug and it has happened on MacBook too. Monterey looks good though. Runs smoother than Big Sur for me.

**Comment by zearp** [comment]
I noticed in your image you have the EHCx controllers visible. They should not be visible if you have applied the UEFI edits and ACPI patches. Not sure if they relate to your usb issue but it means your setup differs from mine. Making it harder to solve things. The UEFI changes make sure everything related to usb is done by thee XHCI controller instead. Using XHCI and disabling EHCx controllers is best practise for hackintosh.

**Comment by zearp** [comment]
This is how it looks on my test machine with Monterey.

![monterey](https://user-images.githubusercontent.com/63272687/135554727-0af02f6f-b161-4dbb-8ebf-610192154d53.png)

(I have manually set one port to internal for the bluetooth part of my Apple Airport card in this machine, this fixes sleep for me.)

**Comment by GCPDetective** [comment]
Thought I messed up for a sec lmao. The pic is from my MacBook, my Optiplex has all ports listed as XHC. Thanks for the heads up though.

Everything was working great in Monterey as I was daily driving that since it was made available to devs. Probably didn't realize how bad Big Sur was until I downgraded a few days ago lol.

**Comment by mgrimace** [comment]
> I hope Monterey GM will be released soon because the beta's sometimes require a fresh install/upgrade using usb installer instead of simply updating from the App Store. I consider this a bug and it has happened on MacBook too. Monterey looks good though. Runs smoother than Big Sur for me.

FYI I was able to update Beta 6 -> Beta 9 using the internal preferences/software update function with the latest EFI (current Oct8/21)  + setting `AdviseFeatures` to `TRUE` in the config.plist.

**Comment by zearp** [comment]
@mgrimace Thanks! 

I have not been around the beta's lately. Waiting for it to be final so I move my repo's to Monterey as default. Good to know this setting might be needed.
