### ISSUE TITLE
OptiPlex 9020 Screen Turns Off When Loading Into GUI Installer

### ISSUE THREAD

**Issue by lazytechnerd** [zearp/OptiHack#77]
Hi,

I should preface this by saying I have done this before but decided to wipe the original hard drive it was on, as I didn't have a use for it, and it wasn't stable.
After trial and error trying to get Ventura to work, I resettled with Monterey, which gave me decent results in the past, but now I can't boot into the installer without the screen losing its signal, but the OptiPlex is still on. I've also tried the fix for the screen staying off after wake, which didn't do anything for me. I don't remember what I did before for it to work first try, besides following the guide **VERY** carefully.
What should I do?
Please help. Thanks!

**Comment by kazuh99** [comment]
Hi, Sorry to hear you're struggling with the install. The guide is pretty bullet-proof so I am surprised you are having issues. Can you please be specific about where you are in the installation process and the steps you have taken. Also can you tell us how you have connected your display to your machine?

**Comment by lazytechnerd** [comment]
Hi,
Thanks for your quick response.
I have my OptiPlex connected to its corresponding monitor directly through its DisplayPort cable, and it was working, until it randomly loses the signal, just before launching the GUI for the installer. The choices I have made during the steps are as follow.
My SMBIOS is Macmini7,1, setting its respective fields to their corresponding serials. This is how I did it before.
I changed the audio layout from 17 to 15. This is how I did it before.
I enabled audio over DisplayPort or HDMI. I don't believe I did this before, but I am not sure.
I then confirmed the Boot List Option in the BIOS was set to UEFI and changed RAID to AHCI. I also did this before.
I then cleared the NVRAM and made the UEFI edits, including setting the DVMT pre-alloc to 64MB, once again I did before.
After rebooting, I booted into the Mac OS Monterey installer, and it was looking good, until the point where, after the end of the lines of text, and the showing of the Apple logo and progress bar, where the signal suddenly cut off, and my monitor went into power-saving mode. I retried multiple times, checked the troubleshooting guide, and followed the instructions with the "screen staying off after wake" section under Screen stuff, to no avail.
I will again mention that this worked fine before, although it was unstable on the desktop, with generally the same settings, except for the audio over DisplayPort. Again, I don't know if I had set that setting in my original setup.
What should I do?

**Comment by zearp** [comment]
Try without making any modifications to the frame buffer or settings beyond serials and try both video outputs. One of them should work, if not you'll have to make your own connector map that matches the 9020 if you can't get any display output.

From what I know the connectors are the same on both machines and you're the first person with this issue. So if you don't change anything in the config except the serials and ethernet mac address. one of the two display ports should give a signal.

What happens is that it switches over to graphical mode and you see nothing because the signal is sent to the "Wrong" place. This usually happens when the frame buffer is not setup or setup properly.

Leave all the other things for post-install as making many changes just creates more places it can go wrong and makes it difficult to help you. You don't need audio over hdmi to install it. Once installed it is much easier to fix things.
