### ISSUE TITLE
Patch for 4K displays

### ISSUE THREAD

**Issue by franklin-yang** [zearp/OptiHack#8]
4K displays didn't work for me until I added this under Root/Kernel/Patch
```
<array>
	<dict>
		<key>Base</key>
		<string></string>
		<key>Comment</key>
		<string>Enable 4k</string>
		<key>Count</key>
		<integer>0</integer>
		<key>Enabled</key>
		<true/>
		<key>Find</key>
		<data>
		AwAiDQADAwMAAAACAAAwAQ==
		</data>
		<key>Identifier</key>
		<string>com.apple.driver.AppleIntelFramebufferAzul</string>
		<key>Limit</key>
		<integer>0</integer>
		<key>Mask</key>
		<data>
		</data>
		<key>Replace</key>
		<data>
		AwAiDQADAwMAAAAEAAAAAw==
		</data>
		<key>ReplaceMask</key>
		<data>
		</data>
		<key>Skip</key>
		<integer>0</integer>
	</dict>
</array>
```
<img width="576" alt="Screen Shot 2020-05-11 at 3 21 42 PM" src="https://user-images.githubusercontent.com/36114251/81602725-1fbe4a80-939b-11ea-8ec8-f32e81296e80.png">

**Comment by zearp** [comment]
Thanks for sharing. I don't have any 4k screens to test. Wonder why it wasn't working though. Maybe the HDMI 2.0 flag (-cdfon) doesn't work (correctly) on DisplayPorts. It should allow for UHD+ resolutions. Might remove the boot flag but won't be adding a patch cuz I can't test them and they can easily break with macOS updates.

**Comment by zearp** [comment]
What exactly does that patch do? Can you share some details on how it works?

I would be careful with patches like this as it could break on macOS updates. This also goes for the TRIM enabler patch, which I will renmove at some point for stability sake. I don't have any 4k screens to test so I dunno if this would apply to everybody or to certain screens.

**Comment by zearp** [comment]
What exactly does that patch do? Can you share some details on how it works?

I would be careful with patches like this as it could break on macOS updates. This also goes for the TRIM enabler patch, which I will remove at some point for stability sake. I don't have any 4k screens to test so I dunno if this would apply to everybody or to certain screens.

**Comment by li3p** [comment]
This patch was used to support single or dual 4K displays, you can find more information on [this page](https://www.tonymacx86.com/threads/dell-optiplex-7020-4k-monitors-on-intel-4600-integrated-gpu.282589/). Since this is the only way to enable 4K displays with HiDPI, I started using this patch since macOS Mojave. It's not harmful for normal 1080p/2k displays.

**Comment by zearp** [comment]
That thread doesn't explain what the patch does and why is the moderator posting an EFI that includes laptop patches for this machine? Seems they have no idea what they're doing. Not to mention all the referral links to make money.

According to Github statistics I've also had some referrals from that thread here but when I visited that topic the posts linking to this repo where gone. Deleted most likely.

If anyone knows what that patch exactly does and how it works please let me know.

**Comment by zearp** [comment]
I checked that thread, seen your post but it doesn't say how the patch works. Can you expand on what it does?

**Comment by li3p** [comment]
check [this thread](https://www.tonymacx86.com/threads/intel-hd-4600-4k-3840-2160-with-seiki-39-4k-display.117665/post-971232)

**Comment by zearp** [comment]
That thread also doesn't explain anything about how this works. After doing al little digging I gathered the following:

0300220D = Platform ID
00030303 = Pipe and port count
00000002 = DVMT allocation (32MB)
00003001 = Framebuffer memory (19MB)

The patch changes the last two options. 

Changing the DVMT from 00000002 to 00000004 would set a 64MB DVMT allocation, not sure if that is needed because we [changed](https://github.com/zearp/OptiHack#set-dvmt-pre-alloc-to-64mb) the DVMT to 64MB (or more) in the BIOS and WEG should automagically see and use that. But maybe I'm wrong in assuming that it does that.

The other one changes the fb memory size from 00003001 (32MB) to 00000003 (48MB). 

Both can be done with WhateverGreen by adding a `framebuffer-stolenmem` option and setting that to 00000003 and `framebuffer-memorycount` and setting that to 00000004
![test](https://user-images.githubusercontent.com/63272687/82554351-0a4cdb80-9b66-11ea-8c7c-04bbb14b8280.png)
 in the config.plist's DeviceProperties section.

It would be nice if you can test if this holds true. Disable the patch and add those two values to the config and see if 4k still works. I would much prefer enabling 4k this way because it won't break when Apple changes the AppleIntelFramebufferAzul.kext in an update.

**Comment by zearp** [comment]
That thread also doesn't explain anything about how this works. After doing al little digging I gathered the following:

0300220D = Platform ID
00030303 = Pipe and port count
00000002 = DVMT allocation (32MB)
00003001 = Framebuffer memory (19MB)

The patch changes the last two options. 

Changing the DVMT from 00000002 to 00000004 would set a 64MB DVMT allocation, not sure if that is needed because we [changed](https://github.com/zearp/OptiHack#set-dvmt-pre-alloc-to-64mb) the DVMT to 64MB (or more) in the BIOS and WEG should automagically see and use that. But maybe I'm wrong in assuming that it does that.

The other one changes the fb memory size from 00003001 (32MB) to 00000003 (48MB). 

Both can be done with WhateverGreen by adding a `framebuffer-stolenmem` option and setting that to 00000003 and `framebuffer-memorycount` and setting that to 00000004 in the config.plist's DeviceProperties section.

It would be nice if you can test if this holds true. Disable the patch and add those two values to the config and see if 4k still works. I would much prefer doing it this way because it won't break when Apple changes the AppleIntelFramebufferAzul.kext in an update.

Hope you can test this and report back, thanks!

![test](https://user-images.githubusercontent.com/63272687/82554427-2e102180-9b66-11ea-9113-68acec8a30ef.png)

**Comment by zearp** [comment]
That thread also doesn't explain anything about how this works. but maybe I want too many details lol. After doing a little digging I gathered the following:

0300220D = Platform ID
00030303 = Pipe and port count
00000002 = DVMT allocation
00003001 = Framebuffer memory

The patch changes the last two values. 

Changing the DVMT from 00000002 to 00000004 would set a 64MB DVMT allocation, not sure if that is needed because we [changed](https://github.com/zearp/OptiHack#set-dvmt-pre-alloc-to-64mb) the DVMT to 64MB (or more) in the BIOS and WEG should automagically see and use that.

But maybe I'm wrong in assuming that WEG does that. If it doesn't see the size this is indeed needed. Also if you've changed the DVMT to some other value this value also needs to change, say you've set it to 128MB then you would need to use 00000008 here.

The other one changes the fb memory size from 00003001 (32MB) to 00000003 (48MB). 

Both can be done with WhateverGreen by adding a `framebuffer-stolenmem` option and setting that to 00000003 and `framebuffer-memorycount` and setting that to 00000004 in the config.plist's DeviceProperties section. 

It would be nice if you can test if this holds true. Disable the patch and add those two values to the config and see if 4k still works. I would much prefer doing it this way because it won't break when Apple changes the AppleIntelFramebufferAzul.kext in an update.

Hope you can test this and report back, thanks!

![82554427-2e102180-9b66-11ea-9113-68acec8a30ef](https://user-images.githubusercontent.com/63272687/82558783-b397cf80-9b6e-11ea-9be0-95088ee39669.png)
